apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
  namespace: default
  labels:
    app: vault
    tier: db
data:
  config.hcl: |
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    storage "consul" {
      address = "consul-consul-0:8500"
      path    = "vault/"
    }
