apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-data
  namespace: default
  labels:
    app: vault
    volume: data
    tier: db
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/vault-data/
