kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault-data
  namespace: default
  labels:
    app: vault
    volume: data
    tier: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: vault
      volume: data
      tier: db
