apiVersion: v1
name: postgresql-statefulset
description: This example deploys a postgresql-statefulset named pgset.
version: 1
appVersion: 1.8.3
keywords:
- postgresql
- postgres
- database
- sql
home: https://www.crunchydata.com/
icon: https://www.crunchydata.com/images/logo.svg
sources:
- https://github.com/CrunchyData/crunchy-containers
